### ISSUE TITLE
[BUG] Documentation coverage should not take into account private methods/properties of class

### ISSUE THREAD

**Issue by EugeneSnihovsky** [compodoc/compodoc#122]
##### **Overview of the issue**

Document coverage show not 100% when I do not write documentation for private methods.

##### **Operating System, Node.js, npm, compodoc version(s)**

Mac OS Sierra 10.12.3
NodeJS 6.9.5
npm 3.10.10
compodoc 0.41

##### **Compodoc installed globally or locally ?**

locally

##### **Motivation for or Use Case**

To work with the application, the user does not need to know about private methods

**Comment by Loster102** [comment]
In addition to that. When I got an empty class, just with the default constructor, but both are documented, there is 0% coverage. Because there are 0/0 statements documented. I think it is a kind of weird behaviour. I would have expected that the coverage is 100% when the class and the constructor is documented.

**Comment by vogloblinsky** [comment]
Fixed in next release, coming soon.

```
/**
 * The test class
 */
export class Test {
    /**
     * the constructor
     */
    constructor() {}
}
```

Gives 2 statements, and 100% coverage

```
/**
 * The test class
 */
export class Test {
    /**
     * the constructor
     */
    constructor() {}

    /**
     *  fakeMethod !!
     *  @example <caption>Usage of fakeMethod</caption>
     *  returns true;
     *  fakeMethod()
     */
    private fakeMethod(): boolean {
        return true;
    }
}
```

Gives also 2 statements, and 100% coverage
