### ISSUE TITLE
[BUG] flickering when navigating in darkmode

### ISSUE THREAD

**Issue by zilahir** [compodoc/compodoc#1397]
If the docs are  generated using: `npx @compodoc/compodoc -p tsconfig.json -n 'hello world'`, when navigating between pages the darkmode is lost for a split of a second, causing a very disturbing white flickering

It's probably related to the dark mote is not beint persisted between page loads. If i have the dark mode on, and navigating, first the toggle goes back to normal mode, and once the page loaded it goes back to dark mode. 

Possibly related to this: #1167 , however that is considered as fixed.

os: osx 14.0
node v20.6.1
npm: 9.8.1

There's no any error or warning on the console when generating the docs, and it works well otherwise, apart from the flickering effect when navigating.

**Comment by vogloblinsky** [comment]
Dark mode is persisted in localstorage. I cannot add an option to persist the dark CSS class in generated pages, because it will be the same for someone who wants the light mode while reading a documentation.
The only enhancement i see is to move the dark mode code in a specific file or even better at the bottom of each generated page.
