### ISSUE TITLE
[BUG] Interface generation missing w/o errors.

### ISSUE THREAD

**Issue by Swiftwork** [compodoc/compodoc#198]
##### **Overview of the issue**

Unsure if I am missing something, but I can't see any interface documentation, which I believe existed previously.

##### **Operating System, Node.js, npm, compodoc version(s)**

Compodoc: 1.0.0-beta.9
Node.js version : v7.5.0
Operating system : Windows 8.1

##### **Angular configuration, a `package.json` file in the root folder**

https://compodoc.github.io/compodoc-demo-todomvc-angular/index.html

##### **Compodoc installed globally or locally ?**

Locally

##### **Motivation for or Use Case**

Missing information

##### **Reproduce the error**

https://compodoc.github.io/compodoc-demo-todomvc-angular/index.html

##### **Related issues**

Not what I can find.

##### **Suggest a Fix**

Could not see any error and I haven't dwelled deeper into the code yet.

**Comment by vogloblinsky** [comment]
Arf, seems there is a problem with TypeScript parser and interfaces...
I fix that asap.

**Comment by vogloblinsky** [comment]
Ok, the bug is related to this fix https://github.com/compodoc/compodoc/commit/c49138408d0e7d486071bda74c2a20af2c497170
Before starting *.ts files parsing, previously i used the files list form TypeScript program.
To fix the issue with BOM UTF-8 files, i generate myself the list, and start the stuff with it.
Some informations are missing for each file in the list, compared to the original list from TypeScript program.
Work in progress...

**Comment by Swiftwork** [comment]
Great work, what time frame do you see for the next release? :)

**Comment by vogloblinsky** [comment]
Very very soon, i just want to include one last bug in the next beta release. May be next monday or tuesday.
