### ISSUE TITLE
[BUG] beta.14 crashes on parameter properties with documentation

### ISSUE THREAD

**Issue by pavadeli** [compodoc/compodoc#286]
##### **Overview of the issue**

When running compodoc on the following code:
```typescript
export class Works {
    constructor(public property: string) { }
}

export class Fails {
    constructor(
        /** This fails. */
        public property: string,
    ) { }
}
```

I get the following error message:
```
[11:22:52] found          : Works
[11:22:52] RangeError: Invalid array length
[11:22:52] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
```

This bug did not occur in versions before beta.14.

##### **Operating System, Node.js, npm, compodoc version(s)**

OS X
Node.js v8.1.3
npm v4.6.1
compodoc v1.0.0-beta.14

**Comment by pavadeli** [comment]
The reported RangeError is produced by the logger. The actual errormessage is: `ReferenceError: getJSDocTags is not defined: <filename>`

**Comment by csentis** [comment]
@pavadeli Just happened to have the case myself. I was able to fix it in the following way (adapted to your source code):

```
export class FailsNoMore {
    /**
     * Creates and initializes the object created with the class.
     * @param {string} property String of the property.
     */
    constructor(
        public property: string
    ) { }
}
```
The behaviour seems to have been chosen by design: cp. issue #259 (bottom).

As `compodoc` can be a bit picky about trailing commas (`compodoc` widely makes use of arrays), I recommend removing the trialing comma for the sake of your own mental debugging health ;-)

@vogloblinsky This might not necessarily be categorized as a bug. A short documentation on "how a constructor can be documented" might do the trick.

HTH
Christian
