### ISSUE TITLE
[FEATURE] Living Style Guide

### ISSUE THREAD

**Issue by kroeder** [compodoc/compodoc#366]
##### **Overview of the issue**

Is there any plan to offer a living style guide? It feels like compodoc has everything a developer can dream of. The only major thing it is missing (for me) is a living style guide - actual components you can use in the documentation

##### **Motivation for or Use Case**

Make development in a team faster by offering actual component implementations alongside a working code-snippet and all the other great things compodoc currently has implemented.

**Comment by kroeder** [comment]
Is this even the correct use case of compodoc?
When I look at the example it documents an application pretty well but does it work for libraries as well?

If not then my request does not make any sense :)

**Comment by vogloblinsky** [comment]
Hi, this could be a could feature. Do you have an open-source example of such a library ?
I test sometimes Compodoc with Angular UI libraries like primeng or admins like ngx-admin

**Comment by kroeder** [comment]
primeng is a perfect example of a living style guide

https://www.primefaces.org/primeng/#/
In this case all navigation items would be under the "Components" Category of compodoc 

https://www.primefaces.org/primeng/#/button A component detail page would have something like a "Demo" Tab additional to the current compodoc tabs

I forgot the name but there's a react documentation tool that does this pretty well by placing a markdown file in every component folder which allows you to write html / access components for the demo tab

**Comment by aitboudad** [comment]
also check material2 https://material.angular.io/components/autocomplete/examples

**Comment by andreasonny83** [comment]
I would also love to have such a feature available in Compodoc. 
At the moment, the only way I found to achieve that result , is to have a demo app build in parallel of the compodoc one.
This feature would be really useful for building a complete documentation for almost any Angular library

**Comment by Karankang007** [comment]
For angular 2.x + users, try this library: https://github.com/ui-jar/ui-jar

**Comment by hughanderson4** [comment]
https://github.com/socreate/angular-playground

https://github.com/storybooks/storybook

https://github.com/nextbigsoundinc/stylemark

**Comment by ajkandy** [comment]
> https://github.com/socreate/angular-playground
> 
> https://github.com/storybooks/storybook
> 
> https://github.com/nextbigsoundinc/stylemark

Yup. We've looked at all of these in addition to Compodoc . Our use case is:

- Need to have a shared style guide (HTML/CSS, visual design, embed images + media) - either built manually with Markdown-style syntax, or automatically from parsed files
- Need a shared component library with sandboxed live embedded examples (ideally) that we can build automatically when components are added to GitLab, even if it means copying them over / parsing
- Would love to have tools to build interactive examples like Storybook-style "knobs" (similar to Angular Playground's states) and inline try-it editors (CodePen or MDN type), etc.
- Ability to set page hierarchies, taxonomy, categories with a robust search
- Flexible theming (SCSS) / templating (ideally, something like Twig / handlebars?)

Ultimately, we want to build our own internal version of material.io. They use ngdocs + Dgeni but with likely a lot of custom stuff.

**Comment by andrewantar** [comment]
Is this still happening?

**Comment by adamcoard-maximus** [comment]
Our use case and desired end result is very similar to @ajkandy 's, we're making a government style guide.  Tools like ui-jar seem nice but not quite as stable as we'd like to invest heavily in them (at least, they weren't 8mo ago).

Ultimately, it looks like we're going to settle on:

* Creating an additional angular project full of demos that pulls from our library, built to `./demos/`
* Include links to each component demo via ["Live Example Tabs"](https://compodoc.app/guides/tab-configuration.html)
* Customize the theme files of CompoDoc as necessary (we may break out the live examples so they're not a tab but at the top of every page) 

We also considered using something like plunkr for our embeds, but we're hesitant lock-in and dependency on a third party.

All in all it's a lot of work but it seems the most maintainable approach. I welcome any feedback and ask if anyone has done something similar.  It would be a lot easier for us if compodoc could instantiate the component itself instead of us having to write a whole demo application and manually associate each compodoc page with the demo application's URL for each component.

**Comment by pstephenwille** [comment]
I'm just investigating the NG doc options and one need I have is, in addition to a live demo is, the ability to mock out the HttpClientModule on the component for the demo page.
