### ISSUE TITLE
[FEATURE] Embed images using @comments

### ISSUE THREAD

**Issue by taat** [compodoc/compodoc#421]
##### **Overview of the issue**

Now we can embed images in .md files, an option to embed image on particular component or module page would be needed.

Eg. add some component screenshots on this page:

https://compodoc.github.io/compodoc-demo-todomvc-angular/components/AboutComponent.html

(One or more images on the top of the page, or on a separate tab)

##### **Suggest a Fix**

Option A:

If a component directory contains image files, eg.

- src/module-name/component-name/some-image.png
- src/module-name/component-name/other-image.jpg

Link them automatically at the top of the component doc page

Option B:

Use some annotations to embed images, eg.

@image some-image.png "Image Description" "Image title" "Image Alt"
@image other-image.png "Image Description" "Image title" "Image Alt"

This might be cool for videos or mp3s as well.

**Comment by minareth** [comment]
So, is there a way to add some component screenshots on this page:

https://compodoc.github.io/compodoc-demo-todomvc-angular/components/AboutComponent.html

(One or more images on the top of the page, or on a separate tab) ?? 

I'm sorry, but I need to understand how to solve this for myself atm. TY

**Comment by benjamincharity** [comment]
@minareth I don't believe there is a way currently; but there is a fairly simple workaround:

If you create a markdown file with the same name as the component (in the same directory) it will be added as a 'README' tab to that page.

```
/myDirectory
  my.component.ts
  my.component.html
  my.component.md
```

Here is how the tab will look:
![screen shot 2018-05-04 at 8 31 43 am](https://user-images.githubusercontent.com/270193/39628008-a8bf4224-4f75-11e8-90e8-6c5f12ffb269.png)

It's just markdown, so you can add anything that markdown supports such as images. You will need to host the images somewhere though (in the repo, cdn, etc).

Compodoc docs on this feature: https://compodoc.github.io/website/guides/tips-and-tricks.html#documentation-of-each-components

Live example in the wild: https://getterminus.github.io/terminus-ui/components/TsAutocompleteComponent.html#readme

**Comment by minareth** [comment]
Thank you very much, Benjamin. You've helped a lot. This looks like nice workaround indeed !



04 мая 2018, 15:35:30, от "Benjamin Charity" <notifications@github.com>: 


@minareth I don't believe there is a way currently; but there is a fairly simple workaround:

If you create a markdown file with the same name as the component (in the same directory) it will be added as a 'README' tab to that page.

/myDirectory
  my.component.ts
  my.component.html
  my.component.md
Here is how the tab will look:


It's just markdown, so you can add anything that markdown supports such as images. You will need to host the images somewhere though (in the repo, cdn, etc).

Compodoc docs on this feature: https://compodoc.github.io/website/guides/tips-and-tricks.html#documentation-of-each-components

Live example in the wild: https://getterminus.github.io/terminus-ui/components/TsAutocompleteComponent.html#readme

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.







-- 
С уважением, Иван.
