### ISSUE TITLE
[FEATURE] Custom Partials Templates

### ISSUE THREAD

**Issue by evertheme** [compodoc/compodoc#70]
Provide the ability to customize the .hbs files in the "templates" directory

**Example:** Modify menu.hbs so .menu-toggler is collapsed when the is loaded.

**Comment by vogloblinsky** [comment]
an option for collapsed menu can be added, it is just for that use-case ?

**Comment by evertheme** [comment]
The ultimate goal is to enable a developer to customize the DOM by pointing to their copy of the "templates" directory. (Like you did for custom styles)

In my case, I would modify page.hbs to include my own css, scripts, etc and modify the [partial].hbs accordingly so I'm not tied to using bootstrap.

Config:
--templates **[dir]**

Read templates:
fs.readFile(path.resolve(**[dir]** + partials[i] + '.hbs'), 'utf8', (err, data) ...
fs.readFile(path.resolve(**[dir]** +'/page.hbs'), 'utf8', (err, data)...

**Comment by evertheme** [comment]
... This may also allow contributors to build custom themes for you.

P.S. Your themes are great! I just need to comply with corporate UI standards.

**Comment by frederikschubert** [comment]
This would also solve https://github.com/compodoc/compodoc/issues/40

**Comment by yihengli** [comment]
Not sure if there is any news regarding this feature request since I do how handy this would be to let other developers customize and enhance the templates.

Recently I am using this awesome project as part of a huge project's documentation. The main project will be hosted by Django with its separate home page. I want to create a **return to hompage** button somewhere on those static pages. The current hack I am using is to write another script to replace all the title on each page with a new element. 

A good example of this feature would be another project I am using as well. [Mkdoc Material - Customizing Themes](https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme)

**Comment by bhofmei** [comment]
Please implement this feature! I want to override the "block-method.hbs" partial to reorder the table rows and update the formatting to something that makes more sense to me. Currently, I have to fork the project, but it would be an incredibly simple (and powerful) fix if I could override the partial like in [jsdoc-to-markdown](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Create-a-custom-partial).

**Comment by vogloblinsky** [comment]
@bhofmei Can you explain what is our re-ordering ? with screenshots if possible.
If it make sense for the majority of users, i could update the current template.
We have performance/memory issues with Handlebars with very large projects, and we are thinking about "may be" switching to a new rendering engine (which support extension of templates)

**Comment by bhofmei** [comment]
Just a heads up. I implemented this--it was really easy and I really wanted it for my own project. I need to write tests then I'll submit a pull request.

**Comment by vogloblinsky** [comment]
Closed by https://github.com/compodoc/compodoc/pull/614
