### ISSUE TITLE
[FEATURE/QUESTION] Generate Unit Test documentation

### ISSUE THREAD

**Issue by macroprog** [compodoc/compodoc#840]
Hello,

It would be usefull to be able to extract the tests documentation also.
For the moment, Compodoc ignores .spec files.

It would allow to follow our unit tests developments and evaluate the ones missing.

Thak you,
Damien

**Comment by fvandangeon** [comment]
+1 
Exposing the describe/it description of a given element into a dedicated tab would be great !

**Comment by rickvandermey** [comment]
You could easily append the coverage.html as a iframe in additional docs.
I've included things such as webpack bundle analyzer, and E2E reports

**Comment by macroprog** [comment]
Thank you for this information but, i can't understand how to use the html files in your GitHub link.
Can you detail that please ?

**Comment by brian428** [comment]
This would be quite helpful for me as well. Not so much to document the tests themselves, but we have a substantial set of helper functions to use in our tests (to create mock data, to trigger events, to wait for specific sequences of Observables to fire, etc.). Having docs would let my team see what spec helper functions are available. 

I could easily limit compodoc to only ingest the "*.helper.spec" files, but right now it's impossible because *.spec is a hardcoded exclusion.

**Comment by brian428** [comment]
Just bumping this because I don't want the bot to close it. I assume it would be fairly easy to add a flag to prevent the automatic exclusion of *.spec files?
