### ISSUE TITLE
[FEATURE] Design System / Living Style Guide

### ISSUE THREAD

**Issue by acoard** [compodoc/compodoc#854]
##### **Overview of the feature**

Compodoc is very close to being able to generate a "Design System" or "Living Style Guide" already. 

A living style guide importantly has:

- **Usable, embedded components directly in the documentation**
- Ample space for design documentation (this can already be handled with custom templates)
- Auto-generated docs for code (already done).

The ability to create a **living style guide**, by having usable components in the documentation itself.  Embeddable demos and code is important, but as is the ability to write design documentation too (e.g. "you should use this component when X, but not Y")

Examples of other design systems.  I've linked to 'Accordion' pages for easy comparisons:

* [United States Government's Official Design System](https://designsystem.digital.gov/components/accordion/)
* [Clarity.Design](https://v2.clarity.design/accordion)
* [PrimeNG](https://www.primefaces.org/primeng/#/accordion)
* [UK Government's Design System](https://design-system.service.gov.uk/components/accordion/)

##### **Motivation for or Use Case**

Design systems are all the rage - on fire with both startups and governments.  There are many large corporations or government agencies which use angular.  Compodoc is a perfect fit for capturing this market and already has most of the functionality required.

By having embedded demos directly in Compodoc, it makes cross-team organization much easier.   The UX team can easily interact with, and document, every single component.

Without this feature, the only way to demo our components is to effectively write an entire "demo" application and link it in the "Examples" tab.  This is possible - and something we've explored - but if we go this route we're temped to just write our bespoke "demo" application to become our design system and replace Compodoc entirely.

##### **Related issues**

Note: this is a re-submission of auto-closed [ticket 366](https://github.com/compodoc/compodoc/issues/366)

https://github.com/compodoc/compodoc/issues/290

https://github.com/compodoc/compodoc/issues/390

#### Additional

**My main question:  Is this something Compodoc plans?**  Or is this something you are firmly staying away from?

I'm not sure how difficult this is to implement, because it does require actually running the source code instead of just statically analyzing it.  If it's prohibitively difficult / out of scope please just let me know so my team can decide how to move forward.

Thank you for the great software,
Adam

**Comment by pburgmer** [comment]
Would be great if compodoc supports this. All other tools like ui-jar and storybook are missing the API documentation feature.

**Comment by shilman** [comment]
Hi @voglobinsky @acoard @pburgmer, I'm happy to announce @kroeder and I have integrated Compodoc into [Storybook Docs](https://medium.com/storybookjs/storybook-5-2-794958b9b111)!

<img width="1524" alt="angular-hero" src="https://user-images.githubusercontent.com/488689/68068679-49663b80-fd92-11e9-9f18-d58c20e5716e.png">

Check out the alpha: https://github.com/storybookjs/storybook/blob/next/addons/docs/angular/README.md

Storybook is the most popular component workshop and we're doubling down on Angular support. We're big Compodoc fans, so it was the natural choice for bringing API docs to Storybook.

We're currently integrating via a static JSON export, and would love to improve the integration [using `--watch` mode](https://github.com/compodoc/compodoc/issues/862), or by other means.

We're also interested in figuring out broader integration, since we see Storybook and Compodoc as overlapping but complementary tools, and we'll be recommending Compodoc to Storybook users.

**Comment by vogloblinsky** [comment]
@shilman thanks for this great feedback and use-case of compodoc ! i know storybook and compodoc overlap a little.
