### ISSUE TITLE
[BUG] Sonarqube reports many error in the generated documents

### ISSUE THREAD

**Issue by pierresh** [compodoc/compodoc#963]
Hello,

As security is more and more important, I have started using [Sonarqube](https://github.com/SonarSource/sonarqube) in an Angular project where the documentation was generated with Compodoc. Compodoc and Sonarqube are two great open source projects but unfortunately, it seems they are conflicting.

##### **Overview of the issue**

Executing Sonarqube on the generated documentation results in many "**Bugs**", "**Vulnerabilities**" and "**Code smells**".

##### **Reproduce the error**
Generate the documentation of an angular project, then scan the generated document with Sonar scanner, then observe the results of the scanning.

##### **Suggest a Fix**
The most important weaknesses found in my documentation are listed below, I suppose they could be easily fixed by modifying templates used to generate the documentation.

`"<strong>" and "<em>" tags should be used  `  [ref](https://rules.sonarsource.com/html/RSPEC-1100)
`"<table>" tags should have a description  `  [ref](https://rules.sonarsource.com/html/RSPEC-1085)
`Tables should have headers  `  [ref](https://rules.sonarsource.com/html/RSPEC-5256)
`Attributes deprecated in HTML5 should not be used  `  [ref](https://rules.sonarsource.com/html/RSPEC-1827)
`Links with "target=_blank" should prevent phishing attacks  `  [ref](https://rules.sonarsource.com/html/type/Vulnerability/RSPEC-5148)

**Comment by segux** [comment]
@pierresh  You should not check the files generated by compodoc, as it is not code written by you or your developers.
I think you should ignore the builds, since the code generators may end up adding undesigned code but you will not have control.

You have added some sonarqube rules that your project does not comply with. But you could have had different ones and it also failed. I don't think composdoc has to adapt to your sonarqube rules.

Rather, it would ignore automatic builds of tools like compodoc.

It is my opinion, I hope it helps you

**Comment by vogloblinsky** [comment]
Yes, ok with @segux, exclude generated content documentation from Sonar scans
